version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twiddly_app
    ports:
      - '5173:5173'
    environment:
      POSTGRES_PRISMA_URL: 'postgres://postgres:postgres@db:5432/twiddly'
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    container_name: twiddly_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twiddly
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
